service: hola-mundo

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline
  - serverless-esbuild

functions:
  hello-world:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
